name: unicaen_timetable
description: Allows the students of the University of Caen Normandie to check their timetable directly from their smartphone.
version: 5.0.3+97
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_week_view: ^1.4.3
  jovial_svg: ^1.1.25
  intl: any
  path_provider: ^2.1.5
  http: ^1.3.0
  background_fetch: ^1.3.8
  flutter_colorpicker: ^1.1.0
  share_plus: ^10.1.4
  rate_my_app: ^2.3.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  scrollable_positioned_list: ^0.3.8
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  eventide: ^0.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
    - 'assets/intro/'
    - 'assets/about/'