name: unicaen_timetable
description: Allows the students of the University of Caen Normandie to check their timetable directly from their smartphone.
version: 5.0.4+98
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_week_view: ^1.4.5
  jovial_svg: ^1.1.28
  intl: any
  path_provider: ^2.1.5
  http: ^1.6.0
  background_fetch: ^1.5.0
  flutter_colorpicker: ^1.1.0
  share_plus: ^12.0.1
  rate_my_app: ^2.3.2
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  scrollable_positioned_list: ^0.3.8
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.4
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  eventide: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
    - 'assets/intro/'
    - 'assets/about/'